In [5]:
import numpy as np
import pandas as pd
import os
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv("IMDB Dataset.csv")

In [7]:
df.head()

review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [8]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [9]:
df["sentiment"].unique()

array(['positive', 'negative'], dtype=object)

In [10]:
df["review"][0]

"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the show is due to the fa

In [11]:
df["review"] = df["review"].str.lower()

In [12]:
import re

In [13]:
def remove_html_tags(text):
    pattern = re.compile("<.*?>")
    return pattern.sub(r"",text)

In [14]:
df["review"]=df["review"].apply(remove_html_tags)

In [15]:
def remove_url(text):
  pattern = re.compile(r"https?://\S+|www\.\S+")
  return pattern.sub(r"",text)

In [16]:
df["review"] = df["review"].apply(remove_url)

In [17]:
import string

In [18]:
exclude = string.punctuation

In [19]:
exclude

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [20]:
def remove_punc(text):
  for char in exclude:
    text = text.replace(char,"")
  return text

In [21]:
df["review"] = df["review"].apply(remove_punc)

In [22]:
from nltk.corpus import stopwords

In [23]:
import nltk

In [24]:
nltk.download("stopwords")


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [25]:
stopwords_english = stopwords.words("english")

In [26]:
def remove_stopwords(text):
  new_list=[]
  for i in text.split():
    if i in stopwords_english:
      new_list.append("")
    else:
      new_list.append(i)
  x = new_list[:]
  new_list.clear()
  return " ".join(x)

In [27]:
df["review"] = df["review"].apply(remove_stopwords)

In [28]:
df["review"][2]

' thought    wonderful way  spend time    hot summer weekend sitting   air conditioned theater  watching  lighthearted comedy  plot  simplistic   dialogue  witty   characters  likable even  well bread suspected serial killer   may  disappointed   realize    match point 2 risk addiction  thought   proof  woody allen  still fully  control   style many  us  grown  lovethis    id laughed  one  woodys comedies  years dare  say  decade  ive never  impressed  scarlet johanson    managed  tone   sexy image  jumped right   average  spirited young womanthis may    crown jewel   career    wittier  devil wears prada   interesting  superman  great comedy  go see  friends'

In [29]:
df["sentiment"] = df["sentiment"].map({"negative":0,"positive":1})

In [30]:
df.head()

review  sentiment
0  one    reviewers  mentioned   watching  1 oz e...          1
1   wonderful little production  filming techniqu...          1
2   thought    wonderful way  spend time    hot s...          1
3  basically theres  family   little boy jake thi...          0
4  petter matteis love   time  money   visually s...          1

In [31]:
df1 = df[:]
df1 = df1[:10000]

In [32]:
X = df1["review"]

In [33]:
y = df1["sentiment"]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [36]:
from sklearn.feature_extraction.text import CountVectorizer

In [37]:
cv = CountVectorizer()

In [38]:
X_train_bow = cv.fit_transform(X_train)
X_test_bow = cv.transform(X_test)

In [39]:
from sklearn.linear_model import LogisticRegression

In [40]:
model = LogisticRegression()

In [41]:
model.fit(X_train_bow,y_train)

LogisticRegression()

In [42]:
y_pred = model.predict(X_test_bow)

In [43]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,f1_score

In [44]:
accuracy_score(y_pred,y_test),precision_score(y_pred,y_test),f1_score(y_pred,y_test),recall_score(y_pred,y_test)

(0.8645, 0.8834661354581673, 0.867481662591687, 0.8520653218059558)

In [45]:
confusion_matrix(y_pred,y_test)

array([[842, 117],
       [154, 887]])

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
rfc = RandomForestClassifier()

In [48]:
rfc.fit(X_train_bow,y_train)

RandomForestClassifier()

In [49]:
y_pred = rfc.predict(X_test_bow)

In [50]:
accuracy_score(y_pred,y_test),precision_score(y_pred,y_test),f1_score(y_pred,y_test),recall_score(y_pred,y_test)

(0.846, 0.8476095617529881, 0.8467661691542289, 0.8459244532803181)

In [51]:
from sklearn.naive_bayes import GaussianNB

In [52]:
gb = GaussianNB()

In [53]:
X_train_bow_gb = X_train_bow.toarray()
X_test_bow_gb = X_test_bow.toarray()

In [54]:
gb.fit(X_train_bow_gb,y_train)

GaussianNB()

In [55]:
y_pred = gb.predict(X_test_bow_gb)

In [56]:
accuracy_score(y_pred,y_test),precision_score(y_pred,y_test),f1_score(y_pred,y_test),recall_score(y_pred,y_test)

(0.634, 0.5527888446215139, 0.6026058631921825, 0.662291169451074)

In [57]:
from sklearn.svm import SVC

In [58]:
svc = SVC()

In [59]:
svc.fit(X_train_bow,y_train)

SVC()

In [60]:
y_pred = svc.predict(X_test_bow)

In [61]:
accuracy_score(y_pred,y_test),precision_score(y_pred,y_test),f1_score(y_pred,y_test),recall_score(y_pred,y_test)

(0.8615, 0.900398406374502, 0.8671462829736211, 0.8362627197039778)

In [62]:
from sklearn.model_selection import cross_val_score, KFold
kf = KFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(model, X_train_bow, y_train, cv=kf, scoring='accuracy')
cv_scores.mean()

np.float64(0.86075)

In [63]:
y_pred = model.predict(X_test_bow)

In [65]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score

In [66]:
roc_auc_score(y_pred,y_test)

np.float64(0.8650316181501104)

In [67]:
accuracy_score(y_pred,y_test),precision_score(y_pred,y_test),recall_score(y_pred,y_test),f1_score(y_pred,y_test)

(0.8645, 0.8834661354581673, 0.8520653218059558, 0.867481662591687)

In [68]:
df2 = df[:]
df2 = df2[20000:30000]

In [69]:
sample_text = df2["review"]

In [70]:
X_train_bow = cv.fit_transform(X_train)
sample_text_bow = cv.transform(sample_text)

In [71]:
predictions = model.predict(sample_text_bow)

In [72]:
actual_values = df2["sentiment"]

In [73]:
accuracy_score(predictions,actual_values)

0.8571

In [74]:
precision_score(predictions,actual_values)

0.8609154929577465

In [75]:
confusion_matrix(predictions,actual_values)

array([[4170,  711],
       [ 718, 4401]])

In [76]:
final = pd.DataFrame(predictions)

In [77]:
final.to_csv("final.csv",index=False)

In [78]:
unseen_text = ["the actor played his role really well","it was a stupid movie"]

In [79]:
X_train_bow = cv.fit_transform(X_train)
unseen_text_bow = cv.transform(unseen_text)

In [80]:
model.predict(unseen_text_bow)

array([1, 0])